<?php

namespace ApiBundle\Repository;

use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * PhotosRepository
 *
 * This class was generated by the Doctrine ORM Budko. Add your own custom
 * repository methods below.
 */
class PhotosRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Return pagination entity Photos
     * @return Paginator
     */
    public function getPaginatedPhotos()
    {
        $qb = $this->createQueryBuilder('p');
        $paginator = new Paginator($qb->getQuery(), $fetchJoinCollection = true);

        return $paginator;
    }

}
