<?php

namespace ApiBundle\Repository;

/**
 * PhotoTagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhotoTagRepository extends \Doctrine\ORM\EntityRepository
{
}
